# Generated by Django 4.2.19 on 2025-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
